In [155]:
import numpy as np
from scipy import stats
from sklearn.metrics import r2_score, accuracy_score

class DecisionNode:
    def __init__(self, col, split, lchild, rchild):
        self.col = col
        self.split = split
        self.lchild = lchild
        self.rchild = rchild

    def predict(self, x_test):
        # Make decision based upon x_test[col] and split
        
        if x_test[self.col]>=self.split:
            return self.rchild.predict(x_test)
        else:
            return self.lchild.predict(x_test)
        


class LeafNode:
    def __init__(self, y, prediction):
        "Create leaf node from y values and prediction; prediction is mean(y) or mode(y)"
        self.n = len(y)
        self.prediction = prediction
        

    def predict(self, x_test):
        return self.prediction
        ...
        
        


def gini(y):
    """
    Return the gini impurity score for values in y
    Assume y = {0,1}
    Gini = 1 - sum_i p_i^2 where p_i is the proportion of class i in y
    """
    ...
    
    y=list(y)
    p_0=(y.count(0))/len(y)
    p_1=(y.count(1))/len(y)
    p_0_2=p_0**2
    p_1_2=p_1**2
    
    gini=1-(p_0_2 + p_1_2)
    
    return gini

    
    
    
def find_best_split(X, y,loss, min_samples_leaf):
    #y_reshape=np.reshape(y,(np.shape(y)[0],1)) #reshaping so that dimensions align
    #Xy=np.hstack((X,y_reshape))                #stacking X along with y
    loss_list=[]
    
    feature=-1
    split=-1
    best_loss=loss(y)
        
    if loss==np.var:
        
        for i in range(np.shape(X)[1]):
            loss_list_temp=[]
            #Xy_t=Xy[:,[i,-1]]                      #stacking columns of X with y, turn by turn
            #x_sorted_asc = Xy_t[Xy_t[:, 0].argsort()] #sorting on first column
            #for j in range(np.shape(x_sorted_asc[0])):
            #print(x_sorted_asc)
            #print(np.shape(x_sorted_asc))
            split_vals=np.random.choice(X[:,i], size = 11, replace = False, p = None)
            for j in split_vals:
                
                y_left=y[X[:,i]<j]
                y_right=y[X[:,i]>=j]
                
                len1=np.shape(y_left)[0]
                len2=np.shape(y_right)[0]
                
                if (len1 < min_samples_leaf) or (len2 < min_samples_leaf):
                    continue
                        
                else:
                    err1=np.var(y_left)
                    err2=np.var(y_right)
                    #len1=np.shape(x_sorted_asc[:j,1])[0]
                    #len2=np.shape(x_sorted_asc[j:,1])[0]
            

            
                    loss=(len1*err1 + len2*err2)/(len1+len2)
                    if loss==0:
                        return i,j
                        break
                        
                    else:    
                        loss_list.append(([loss,i,j]))
        
            #loss_list.append(loss_list_temp)
        
        arr=np.array(loss_list)
        m=np.min(arr[:,0])  #Min loss 
        best_split=(arr[arr[:,0]==m][0])
        
        if m<best_loss:
            
            #best_split =arr[arr[:,0]==m] 
            feature=best_split[1]
            split=best_split[2]
            best_loss=best_split[0]
        
        
        
            
        return feature,split
    
    else:
        
        
        for i in range(np.shape(X)[1]):
            loss_list_temp=[]
            #Xy_t=Xy[:,[i,-1]]                      #stacking columns of X with y, turn by turn
            #x_sorted_asc = Xy_t[Xy_t[:, 0].argsort()] #sorting on first column
            #for j in range(np.shape(x_sorted_asc[0])):
            #print(x_sorted_asc)
            #print(np.shape(x_sorted_asc))
            split_vals=np.random.choice(X[:,i], size = 11, replace = False, p = None)
            for j in split_vals:
                
                y_left=y[X[:,i]<j]
                y_right=y[X[:,i]>=j]
                
                len1=np.shape(y_left)[0]
                len2=np.shape(y_right)[0]
                
                if (len1 < min_samples_leaf) or (len2 < min_samples_leaf):
                    continue
                        
                else:
                    err1=genie(y_left)
                    err2=genie(y_right)
                    #len1=np.shape(x_sorted_asc[:j,1])[0]
                    #len2=np.shape(x_sorted_asc[j:,1])[0]
            

            
                    loss=(len1*err1 + len2*err2)/(len1+len2)
                    if loss==0:
                        return i,j
                        break
                        
                    else:    
                        loss_list.append(([loss,i,j]))
                        
                        
        arr=np.array(loss_list)
        m=np.min(arr[:,0])  #Min loss 
        best_split=(arr[arr[:,0]==m][0])
        
        if m<best_loss:
            
            #best_split =arr[arr[:,0]==m] 
            feature=best_split[1]
            split=best_split[2]
            best_loss=best_split[0]
        
        
        
            
        return feature,split
                        
        
           
def find_best_split_2(X, y,loss, min_samples_leaf):
    
    dict_best_split = {"feature": -1, "split": -1, "best_loss": loss(y)}
    k = 11

    for col_index in range(len(X[0])):
        list_candidates = np.random.choice(X[:, col_index], k)
        for split_val in list_candidates:
            arr_y_left = y[np.where(X[:, col_index] < split_val)]
            arr_y_right = y[np.where(X[:, col_index] >= split_val)]

            int_yl_cnt = len(arr_y_left)
            int_yr_cnt = len(arr_y_right)

            if (int_yl_cnt < min_samples_leaf) | (int_yr_cnt < min_samples_leaf):
                continue

            split_loss = ((int_yl_cnt * loss(arr_y_left)) + (int_yr_cnt * loss(arr_y_right)))/(int_yl_cnt + int_yr_cnt)
            if split_loss == 0:
                return col_index, split_val
            if split_loss < dict_best_split["best_loss"]:
                dict_best_split["feature"] = col_index
                dict_best_split["split"] = split_val
                dict_best_split["best_loss"] = split_loss
    return dict_best_split["feature"], dict_best_split["split"]

        
               
            #for split in range(np.min(X_t),np.max(X_t)):    
class DecisionTree621:
    def __init__(self, min_samples_leaf=1, loss=None):
        self.min_samples_leaf = min_samples_leaf
        self.loss = loss # loss function; either np.var for regression or gini for classification
        
    def fit(self, X, y):
        """
        Create a decision tree fit to (X,y) and save as self.root, the root of
        our decision tree, for  either a classifier or regression.  Leaf nodes for classifiers
        predict the most common class (the mode) and regressions predict the average y
        for observations in that leaf.
        This function is a wrapper around fit_() that just stores the tree in self.root.
        """
        self.root = self.fit_(X, y)


    def fit_(self, X, y):
        """
        Recursively create and return a decision tree fit to (X,y) for
        either a classification or regression.  This function should call self.create_leaf(X,y)
        to create the appropriate leaf node, which will invoke either
        RegressionTree621.create_leaf() or ClassifierTree621.create_leaf() depending
        on the type of self.
        This function is not part of the class "interface" and is for internal use, but it
        embodies the decision tree fitting algorithm.
        (Make sure to call fit_() not fit() recursively.)
        """
        ...
        
        if np.shape(X)[0] <= self.min_samples_leaf or np.shape(np.unique(X, axis=0)[0])==1:
            return self.create_leaf(y)
        
        col,split=find_best_split(X,y,self.loss,self.min_samples_leaf)
        
        if col==-1:
            return self.create_leaf(y)
        else:
        #node=DecisionNode(col,split,fit_(self,X,y)
            y_reshape=np.reshape(y,(np.shape(y)[0],1)) #reshaping so that dimensions align
            Xy=np.hstack((X,y_reshape))
            
            
            
            lchild=self.fit_(Xy[Xy[:,col]<split][:,:-1],Xy[Xy[:,col]<split][:,-1])
            rchild=self.fit_(Xy[Xy[:,col]>=split][:,:-1],Xy[Xy[:,col]>=split][:,-1])
            
            tree=DecisionNode(col,split,lchild,rchild)
            
            return tree
        
                 

    def predict(self, X_test):
        """
        Make a prediction for each record in X_test and return as array.
        This method is inherited by RegressionTree621 and ClassifierTree621 and
        works for both without modification!
        """
        ...
        prediction_list=[]
        
        for x in X_test:
            prediction_list.append(self.root.predict(x))
        return np.array(prediction_list)
        
class RegressionTree621(DecisionTree621):
    def __init__(self, min_samples_leaf=1):
        super().__init__(min_samples_leaf, loss=np.var)

    def score(self, X_test, y_test):
        "Return the R^2 of y_test vs predictions for each record in X_test"
        ...
        predictions=self.predict(X_test)
        
        return r2_score(predictions,y_test)

    def create_leaf(self, y):
        """
        Return a new LeafNode for regression, passing y and mean(y) to
        the LeafNode constructor.
        """
        leaf=LeafNode(y,np.mean(y))
        
        return leaf
        


class ClassifierTree621(DecisionTree621):
    def __init__(self, min_samples_leaf=1):
        super().__init__(min_samples_leaf, loss=gini)

    def score(self, X_test, y_test):
        "Return the accuracy_score() of y_test vs predictions for each record in X_test"
        ...
        predictions=self.predict(X_test)
        
        return accuracy_score(predictions,y_test)
        
        

    def create_leaf(self, y):
        """
        Return a new LeafNode for classification, passing y and mode(y) to
        the LeafNode constructor. Feel free to use scipy.stats to use the mode function.
        """
        ...
        
        leaf=LeafNode(y,stats.mode(y).mode[0])
        
        return leaf
        

In [156]:
list1=[]
list2=[]
for i in range(100):
 list2.append(find_best_split_2(X,y,np.var,1))
 list1.append(find_best_split(X,y,np.var,1))

In [157]:
list1

[(12.0, 9.68),
 (12.0, 9.74),
 (12.0, 7.85),
 (12.0, 9.54),
 (5.0, 6.943),
 (12.0, 9.88),
 (5.0, 6.975),
 (12.0, 9.16),
 (12.0, 8.93),
 (12.0, 9.68),
 (12.0, 9.54),
 (12.0, 10.19),
 (5.0, 6.852),
 (5.0, 6.943),
 (5.0, 6.98),
 (12.0, 7.85),
 (5.0, 6.842),
 (5.0, 6.98),
 (12.0, 10.15),
 (5.0, 6.98),
 (12.0, 7.53),
 (5.0, 6.826),
 (12.0, 10.16),
 (12.0, 7.73),
 (12.0, 9.68),
 (5.0, 6.951),
 (5.0, 6.833),
 (12.0, 10.11),
 (12.0, 7.53),
 (12.0, 7.85),
 (5.0, 6.86),
 (5.0, 6.854),
 (5.0, 6.975),
 (12.0, 10.19),
 (5.0, 6.842),
 (12.0, 9.97),
 (12.0, 8.1),
 (12.0, 9.04),
 (12.0, 10.16),
 (12.0, 7.79),
 (12.0, 9.55),
 (5.0, 6.98),
 (5.0, 6.976),
 (12.0, 9.09),
 (12.0, 7.9),
 (12.0, 9.93),
 (5.0, 6.897),
 (5.0, 7.088),
 (5.0, 6.951),
 (12.0, 9.88),
 (5.0, 6.975),
 (5.0, 6.982),
 (12.0, 7.54),
 (5.0, 6.982),
 (5.0, 6.975),
 (5.0, 6.8),
 (5.0, 6.957),
 (5.0, 6.854),
 (12.0, 9.04),
 (12.0, 7.56),
 (5.0, 6.826),
 (5.0, 6.968),
 (5.0, 6.852),
 (12.0, 10.19),
 (5.0, 6.849),
 (5.0, 6.816),
 (12.0, 9.67

In [158]:
list2
            

[(12, 9.62),
 (12, 7.54),
 (12, 7.67),
 (12, 9.8),
 (5, 6.975),
 (12, 8.05),
 (12, 9.97),
 (12, 9.16),
 (12, 10.19),
 (5, 6.854),
 (12, 9.97),
 (5, 6.871),
 (5, 7.088),
 (12, 9.62),
 (5, 6.826),
 (12, 7.6),
 (5, 6.98),
 (12, 10.26),
 (5, 6.852),
 (5, 6.968),
 (5, 7.014),
 (12, 9.74),
 (12, 8.01),
 (5, 6.98),
 (5, 6.852),
 (5, 6.8),
 (5, 6.957),
 (12, 9.67),
 (5, 6.943),
 (12, 8.05),
 (5, 7.061),
 (12, 8.81),
 (12, 9.64),
 (5, 7.014),
 (12, 7.51),
 (5, 6.939),
 (12, 9.97),
 (5, 6.976),
 (5, 6.98),
 (5, 7.007),
 (12, 10.15),
 (12, 8.94),
 (5, 6.874),
 (5, 6.968),
 (12, 10.11),
 (5, 6.976),
 (12, 10.21),
 (12, 7.67),
 (12, 9.97),
 (12, 9.97),
 (5, 6.976),
 (12, 7.79),
 (12, 10.21),
 (12, 9.64),
 (5, 6.975),
 (12, 7.74),
 (12, 9.69),
 (12, 9.67),
 (12, 9.43),
 (5, 6.98),
 (5, 6.951),
 (5, 6.833),
 (12, 8.88),
 (5, 6.879),
 (12, 7.73),
 (5, 6.854),
 (12, 9.8),
 (12, 10.21),
 (5, 6.943),
 (5, 6.852),
 (5, 6.976),
 (5, 6.849),
 (5, 6.943),
 (12, 9.59),
 (12, 9.55),
 (5, 6.957),
 (5, 6.849),
 

In [66]:
Xy[Xy[2]<10][:,:-1],Xy[Xy[col]<10][:,-1]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 506 but corresponding boolean dimension is 14

In [67]:
np.shape(Xy)

(506, 14)

In [68]:
np.shape(Xy[Xy[:,2]<10][:,:-1])

(270, 13)

In [69]:
Xy[Xy[:,col]<split][:,:-1],Xy[Xy[:,col]<split][:,-1]

(array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 1

In [70]:
np.shape(Xy[Xy[:,2]<10][:,-1])


(270,)

In [71]:
from sklearn.datasets import load_boston, load_iris, load_wine, load_breast_cancer, fetch_california_housing
X, y = load_boston(return_X_y=True)


In [144]:
find_best_split(X,y,np.var,1)

(12.0, 9.88)

In [73]:
np.shape(X[:,0])   #Column 1

(506,)

In [74]:
np.shape(X[:,1])

(506,)

In [89]:
X_test=X[:,1]

y_reshape=np.reshape(y,(np.shape(y)[0],1))
Xy=np.hstack((X,y_reshape))

Xy[:,[0,-1]][:,-1]==y

#define new matrix with rows sorted in ascending order by values in second column
x_sorted_asc = Xy[Xy[:, 0].argsort()]
x_sorted_asc

array([[6.32000e-03, 1.80000e+01, 2.31000e+00, ..., 3.96900e+02,
        4.98000e+00, 2.40000e+01],
       [9.06000e-03, 9.00000e+01, 2.97000e+00, ..., 3.94720e+02,
        7.85000e+00, 3.22000e+01],
       [1.09600e-02, 5.50000e+01, 2.25000e+00, ..., 3.94720e+02,
        8.23000e+00, 2.20000e+01],
       ...,
       [6.79208e+01, 0.00000e+00, 1.81000e+01, ..., 3.84970e+02,
        2.29800e+01, 5.00000e+00],
       [7.35341e+01, 0.00000e+00, 1.81000e+01, ..., 1.64500e+01,
        2.06200e+01, 8.80000e+00],
       [8.89762e+01, 0.00000e+00, 1.81000e+01, ..., 3.96900e+02,
        1.72100e+01, 1.04000e+01]])

In [44]:
np.max(X[:,12])

37.97

In [30]:
for i in range(np.shape(X)[1]):
    print(X[:,i])

In [ ]:
np.sort

In [46]:
np.shape(y)

(506,)

In [79]:
def find_best_split(X, y,loss, min_samples_leaf):
    y_reshape=np.reshape(y,(np.shape(y)[0],1)) #reshaping so that dimensions align
    Xy=np.hstack((X,y_reshape))                #stacking X along with y
    loss_list=[]
    split_indices=np.random.choice(np.shape(X)[0], size = 11, replace = False, p = None)
    feature=-1
    split=-1
    best_loss=loss(y)
        
    if loss==np.var:
        
        for i in range(np.shape(X)[1]):
            loss_list_temp=[]
            Xy_t=Xy[:,[i,-1]]                      #stacking columns of X with y, turn by turn
            x_sorted_asc = Xy_t[Xy_t[:, 0].argsort()] #sorting on first column
            #for j in range(np.shape(x_sorted_asc[0])):
            #print(x_sorted_asc)
            #print(np.shape(x_sorted_asc)) 
            for j in split_indices:
                
                if np.shape(x_sorted_asc[:j,1])[0]<min_samples_leaf:
                    continue
                        
                else:
                    err1=np.var(x_sorted_asc[:j,1])
                    err2=np.var(x_sorted_asc[j:,1])
                    len1=np.shape(x_sorted_asc[:j,1])[0]
                    len2=np.shape(x_sorted_asc[j:,1])[0]
            

            
                    loss=(len1*err1 + len2*err2)/(len1+len2)
                    if loss==0:
                        return i,j
                        break
                        
                    else:    
                        loss_list_temp.append((loss,i,j))
        
            loss_list.append(loss_list_temp)
        
        arr=np.array(loss_list)
        m=np.min(arr[:,:,0])  #Min loss 
        #best_split=(arr[arr[:,:,0]==m][0],arr[arr[:,:,0]==m][1])
        if m<best_loss:
            
            best_split =arr[arr[:,:,0]==m] 
            feature=best_split[0][1]
            split=best_split[0][2]
            best_loss=best_split[0][0]
        
            
        return feature,split
    
    else:
        
            for i in range(np.shape(X)[1]):
                loss_list_temp=[]
                Xy_t=Xy[:,[i,-1]]                      #stacking columns of X with y, turn by turn
                x_sorted_asc = Xy_t[Xy_t[:, 0].argsort()] #sorting on first column
                #for j in range(np.shape(x_sorted_asc[0])):
                #print(x_sorted_asc)
                #print(np.shape(x_sorted_asc)) 
                for j in split_indices:
                
                    if np.shape(x_sorted_asc[:j,1])[0]<min_samples_leaf:
                        continue
                        
                    else:
                        err1=np.var(x_sorted_asc[:j,1])
                        err2=np.var(x_sorted_asc[j:,1])
                        len1=np.shape(x_sorted_asc[:j,1])[0]
                        len2=np.shape(x_sorted_asc[j:,1])[0]
            

            
                        loss=(len1*err1 + len2*err2)/(len1+len2)
                        if loss==0:
                            return i,j
                            break
                        
                        else:    
                            loss_list_temp.append((loss,i,j))
        
            loss_list.append(loss_list_temp)
        
            arr=np.array(loss_list)
            m=np.min(arr[:,:,0])  #Min loss 
            #best_split=(arr[arr[:,:,0]==m][0],arr[arr[:,:,0]==m][1])
            if m<best_loss:
            
                best_split =arr[arr[:,:,0]==m] 
                feature=best_split[0][1]
                split=best_split[0][2]
                best_loss=best_split[0][0]
        
            
            return feature,split
        
        
    
        
            
            
            
            

                
            
        
        
        
    

In [372]:
find_best_split(X,y,gini,10)
#m=np.min(arr[:,:,0])
#arr[arr[:,:,0]==m]
 #Xy_t[Xy_t[:, 0].argsort()]
    


(-1, -1)

In [262]:
lis=[13,54,546,2,10]

In [123]:
min(lis)

2

In [234]:
DecisionNode(1,2)

TypeError: __init__() missing 2 required positional arguments: 'lchild' and 'rchild'

In [237]:
np.random.choice( [1,2,3,5,6,7] , size = 3, replace = False, p = None)

array([2, 6, 5])

In [1]:
X, y = load_wine(return_X_y=True)

NameError: name 'load_wine' is not defined

In [383]:
find_best_split(X,y,np.var,10)

(6.0, 64.0)

In [396]:
tree=DecisionTree621

In [402]:
tree.fit(X,y)

TypeError: fit() missing 1 required positional argument: 'y'

In [26]:
 X, y = load_boston(return_X_y=True)

In [36]:
col,split=find_best_split(X, y,np.var, 1)
col=int(col)

In [37]:
Xy[Xy[:,col]<split][:,:-1],Xy[Xy[:,col]<split][:,-1]

(array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 1